### ISSUE TITLE
Two way replication

### ISSUE THREAD

**Issue by JimmyBoh** [karissa/hyperdiscovery#11]
I have a pretty simple example running with `hypercore` that allows peers to connect. All peers can read just fine (including live). But it seems as though the only peer who can write to the feed is the original (the one that generated the key). Is this correct? How do I enable two-way replication using `hypercore` (so that all clients end up with all the data)?

**Comment by JimmyBoh** [comment]
After looking at test.js I see that the two swarm instances are called `read` and `write`, so I guess this is behaving correctly. Is this a viable technology for what I'm working towards (distributed, two-way sync)?

**Comment by joehand** [comment]
Yes, that is correct that its all one-way right now. Only the user that creates the feed can write. 

You can check out [hyperdb](https://github.com/mafintosh/hyperdb/) where we are developing multi-writer capabilities. It is built on top of hypercore. Hypercore will always be one-way but we'll have other tools like hyperdb to provide multiple writers to feeds.

**Comment by JimmyBoh** [comment]
I was looking into hyperdb, but I wasn't so sure about the filesystem/folder approach. My ideal use case is to sync all data across the swarm with the ability to iterate that data, possibly in realtime (like hypercore's `createReadStream({live: true})`. 

Using hyperdb would I just use something like ``db.put(`/log/${someGuid}`, entry);`` and then `db.watch('/log', cb)`? Or would I use one of the "create stream" methods?

**Comment by joehand** [comment]
The main concern with multiple writers is conflicts. If we both have one entry then we both write the second entry at the same time, there will be a conflict when we try to sync that feed with each other. Hypercore isn't built to handle those conflicts (and not sure we can handle them except with a centralized resolution mechanism).

Depending on your use case, there may be a few ways around it if order in the log isn't too important. You could have multiple hypercores that are all synced and virtually merged into one. Or try to fit your model into hyperdb.

Not really up to date on hyperdb, so I'd ask there or ping mafintosh/noffle in IRC. But the open PR may be what you're looking for: https://github.com/mafintosh/hyperdb/pull/35

**Comment by JimmyBoh** [comment]
That makes sense, but in my case the order is not actually that important. I think hyperdb will actually do the trick given the right usage. You brought up some good points that made me rethink about hyperdb. Given the right approach it just might do the trick, thanks @joehand!

**Comment by JimmyBoh** [comment]
Just FYI, I was able to accomplish my task using hyperdb! Thanks for the help!

Getting the two-way sync working via hyperdiscovery requires some specific options that would be required every time. Would you guys be interested in a PR that adds hyperdb support to hyperdiscovery? Or would that be better as a standalone project?

**Comment by pvh** [comment]
@JimmyBoh would love to see that patch either way!

**Comment by JimmyBoh** [comment]
Sounds good, I'll create the PR in the next day or so. If it doesn't seem like it fits then no harm done!
