### ISSUE TITLE
This feed is not writable. Did you create it?

### ISSUE THREAD

**Issue by evantahler** [karissa/hyperdiscovery#15]
Hello! I'm new and just getting started here...

When attaching to an existing swarm and trying to write to a hyperdrive, I get the error `This feed is not writable. Did you create it?`.  Are there some settings to allow a newly connected peer to write to the shared "disk"?

Thanks!

**Comment by evantahler** [comment]
to reproduce this:
1) run a idle client which will generate a new archive ID
  * from https://github.com/evantahler/hyperjob/blob/master/examples/idle.js
```bash
> ./examples/idle.js idle
Ready! (version: 0)
Archive Key: cac36adfed94be66532cabe8fdb5359597bf6b72d775a3005329abf7bd988495
```

2) try to run the example client which will try to write and then read a file ("job" in this case)
  * from https://github.com/evantahler/hyperjob/blob/master/examples/client.js
```bash
> ./examples/client.js client cac36adfed94be66532cabe8fdb5359597bf6b72d775a3005329abf7bd988495
Ready! (version: 0)
Archive Key: cac36adfed94be66532cabe8fdb5359597bf6b72d775a3005329abf7bd988495
Error: Error: listen EADDRINUSE :::3282
(node:46082) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: This feed is not writable. Did you create it?
```

**Comment by karissa** [comment]
Hey @evantahler, you might want to use hyperdb instead, which has a multiple writers feature. There is also an experimental hyperdrive implementation with hyperdb -- where is that @mafintosh @jimpick @joehand ?

**Comment by evantahler** [comment]
Thanks @karissa! I'll give that a shot

**Comment by jimpick** [comment]
The multiwriter branch is at: https://github.com/mafintosh/hyperdrive/tree/hyperdb-backend

**Comment by evantahler** [comment]
I've given hyperDB a shot, and while there is no explicit warning given now, it still seems that a peer cannot modify the data written by another node.  Also, it seems that if the initial member isn't doing the writing, it will never be able to read the writes of a peer.

**Comment by jimpick** [comment]
@evantahler That sounds odd. It might be a good idea to open an issue on hyperdb. Possibly .authorize(<key>) wasn't called?

**Comment by evantahler** [comment]
Yes, that was it! I was needing to call `authorize()` on the initial source database for all connecting peers.

The readme for hyperdiscovery says:

> A hyperdb database must be ready before attempting to connect to the swarm. When download is enabled the swarm will automatically db.authorize() all connecting peers.

... which I guess isn't the case?  Also, I would recommend rather than letting a peer appear to be able to write to a local version of the database, I would prevent writes if that peer isn't authorized (throw an error)

**Comment by evantahler** [comment]
To clarify the Readme, I assume that this was how I was supposed to "enable download"

`this.swarm = swarm(this.database, {port: this.requestedPort, download: true, upload: true})`

**Comment by pfrazee** [comment]
That's incorrect info that got left-over in a PR, see https://github.com/karissa/hyperdiscovery/pull/12
