### ISSUE TITLE
Add examples to show how discovery.leave works

### ISSUE THREAD

**Issue by ZhouHansen** [karissa/hyperdiscovery#24]
I'm trying out how `discovery.leave` works, but failed.

Computer A is the writer: 
```js
var hypercore = require('hypercore')
var discovery = require('hyperdiscovery')

var feed = hypercore('./data', {valueEncoding: 'utf-8'})

feed.on('ready', () => {
  var sw = discovery()
  feed.append('\ncool')
  sw.add(feed)
  sw.leave(feed.discoveryKey.toString('hex'))
})
```

Computer B replicate the archive:
```js
var hypercore = require('hypercore')
var discovery = require('hyperdiscovery')

var feed = hypercore(
  './data',
  '2e7be17277e5b0799408fd022038d5ca1a3586df88db8dc3e736b5977f1a52e9',
  {
    valueEncoding: 'utf-8'
  }
)

feed.on('ready', () => {
  var sw = discovery()
  sw.add(feed)
})

```

I expect that after `sw.leave(feed.discoveryKey.toString('hex'))` executed on computer A, data 'cool' will not be replicated to Computer B. But replication still happened.

So, if there're some more examples will be help.

**Comment by RangerMauve** [comment]
Leave doesn't close existing connections, I think.

**Comment by ZhouHansen** [comment]
Not sure the purpose of Leave.

**Comment by RangerMauve** [comment]
I think it's to stop announcing and receiving new connections.

**Comment by ZhouHansen** [comment]
It still seems to receive new connections. I updated the code example above.

**Comment by joehand** [comment]
It should close existing connections also.

Please check out my PR to see if that fixes the issue (I tested locally and it does). Would be fantastic if you'd like to add test too =)

**Comment by ZhouHansen** [comment]
It fixes the issue, I will add a test for it.
